NGKS_Shop/urls.py
from django.conf.urls import url, include
from core.views import *
from django.contrib.auth.views import logout

urlpatterns = [
    #ecommerce
    url(r'^$', index, name='index'),
    url(r'^lista_produtos/', lista_produtos, name='lista_produtos'),
    url(r'^categoria/(?P<slug>[\w_-]+)/$', loja_categoria, name='loja_categoria'),
    url(r'^produtos/(?P<slug>[\w_-]+)/$', loja_produto, name='loja_produto'),
    url(r'^registro/', registro, name='cadastro_cliente'),
    url(r'^login/$', loginEcommerce, name='loginEcommerce'),
    url(r'^logout/$', logout, {'next_page': 'index'} ,name='logout'),
    url(r'^contato/$', contato,name='contato'),
    url(r'^checkout/', include(('checkout.urls', 'checkout'), namespace='checkout')),
    #administrativo
    url(r'^principal/$', principal, name='principal'),
    url(r'^sgu/', include(('SGU.urls', 'sgu'), namespace='sgu')),
    url(r'^estoque/$', estoque, name='estoque'),
    url(r'^fluxo/$', fluxo, name='fluxo'),
    url(r'^pedidos/$', pedidos, name='pedidos'),
    url(r'^catalogo/', include(('catalogo.urls', 'catalogo'), namespace='catalogo')),
]

SGU/urls.py
from django.conf.urls import url
from SGU.views import *
from django.contrib.auth.views import login,logout
from SGU import auth as auth_views 

urlpatterns = [
    url(r'^$', sgu, name='sgu'),
    url(r'^chg_pass/', chg_pass, name='chg_pass'),#verificar essa URL
    url(r'^(?P<username>.*)/detalhes', detalhes, name='detalhes'),
    url(r'^cadastro_usuario/', cadastro_usuario, name='cadastro_usuario'),
    url(r'^login_admin/$', loginAdminPanel, name='login'),
    url(r'^logout/', logout, {'next_page': 'sgu:login'} ,name='logout'),
    url(r'^erro_acesso/', erro_acesso, name='erro_acesso'),
    url(r'^password_reset/$', auth_views.password_reset, {'subject_template_name': 'password_reset_subject.txt'}, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
]

SGU/models.py
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager 
from django.urls import reverse

# Create your models here. 

class UsuarioManager(BaseUserManager):
    use_in_migrations = True
    def _create_user(self, username, password, **extra_fields):
        if not username:
            raise ValueError('Username precisa ser preenchido')
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, password=None, **extra_fields):
        return self._create_user(username, password, **extra_fields)

    def create_superuser(self, username, password, **extra_fields):
        return self._create_user(username, password, **extra_fields)

 

class Usuario(AbstractBaseUser):
    nome = models.CharField(max_length=100)
    username = models.CharField(max_length=100, unique=True)   
    email = models.CharField(max_length=100, unique=True)
    tipo = models.CharField(max_length=1)
    password = models.CharField(max_length=150)
    is_active = models.BooleanField(default=True)
    validacao = models.CharField(max_length=150, blank=True)

    USERNAME_FIELD = 'username' 
    REQUIRED_FIELDS = ['email'] 

    objects = UsuarioManager()

    @property
    def is_staff(self):
        return self
    
    def has_perm(self, perm, obj=None):
        return True
    def has_module_perms(self, app_label):
        return True

    def get_short_name(self):
        return self.nome

    def get_full_name(self):
        return self.nome

    def __unicode__(self):
        return self.nome
    
    def get_absolute_url(self):
        return reverse('sgu:detalhes', kwargs={'username':self.username})

    class Meta:
        ordering = ['nome']

class Cliente(Usuario):
    cep = models.BigIntegerField()
    cpf = models.BigIntegerField()

class Grupos(models.Model):
    nome = models.CharField(max_length=50)
    link = models.CharField(max_length=50)

    def __str__(self):
        return self.nome


class Permissions(models.Model):
    groups = models.CharField(max_length=50)
    usuario = models.ForeignKey('usuario',
    on_delete=models.CASCADE,)
    
    def __str__(self):
        return self.groups

SGU/forms.py
from django import forms
from django.forms import ModelForm
from SGU.models import Usuario, Cliente
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext, gettext_lazy as _

class form_usuario(ModelForm):
    password = forms.CharField(label='senha', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Confirmar senha', widget=forms.PasswordInput())
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }
    class Meta():
        model = Usuario
        fields = ['username', 'nome', 'email', 'password', 'password2']
    
    def clean_password2(self):
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if password and password2 and password != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(form_usuario, self).save(commit=False)
        user.tipo = 'E'
        user.set_password(user.password)
        if commit:
            user.save()
        return user

class form_cliente(ModelForm):
    password = forms.CharField(label='senha', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Confirmar senhar',widget=forms.PasswordInput())
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }
    class Meta():
        model = Cliente
        fields = ['nome', 'username', 'email', 'password', 'password2', 'cpf', 'cep']

    def clean_password2(self):
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if password and password2 and password != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2
    def save(self, commit=True):
        user = super(form_cliente, self).save(commit=False)
        user.tipo = 'C'
        user.set_password(user.password)
        if commit:
            user.save()
        return user
        
class LoginForm(forms.Form):
    username = forms.CharField(label=(u'Username'))
    password = forms.CharField(label=(u'Password'), widget=forms.PasswordInput(render_value=False))

SGU/views.py
from django.shortcuts import render_to_response, render
from django.http import HttpResponseRedirect # Funcao para redirecionar o usuario
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator
from SGU.forms import form_usuario, LoginForm
from SGU.models import Grupos, Usuario, Permissions
from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth.views import login
from django.views.generic import CreateView
from src.usuario import Gerencia_usuario, Gerencia_permissao
from django.urls import reverse, reverse_lazy

# Create your views here.

User_model = get_user_model()

def erro_acesso(request):
    return render(request, "erro_acesso.html")

def checa_sgu(request):
    return 'SGU' in Gerencia_permissao.Pega_grupo(request)

@login_required(login_url='sgu:login')
@user_passes_test(checa_sgu, login_url='sgu:erro_acesso', redirect_field_name=None)
def sgu(request):
    contexto = {
        "users" : Usuario.objects.all()
    } 
    delete = request.POST.get("delete")
    if delete:
        Gerencia_usuario.Deleta_usuario(delete)
    return render(request, "sgu.html", contexto)

'''
class View_Registro(CreateView):
    @method_decorator(user_passes_test(checa_sgu, login_url='sgu:erro_acesso', redirect_field_name=None))
    @method_decorator(login_required(login_url='sgu:login'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)    
    form_class = form_usuario
    template_name = 'cadastro_usuario.html'
    model = User_model
    success_url = reverse_lazy('sgu:sgu')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['grupos'] = Grupos.objects.all()
        return context

registro_usuario = View_Registro.as_view()
'''
@login_required(login_url='sgu:login')
@user_passes_test(checa_sgu, login_url='sgu:erro_acesso', redirect_field_name=None)
def cadastro_usuario(request):    
    if request.method == 'POST':
        form = form_usuario(request.POST)
        if form.is_valid():
            Gerencia_usuario.Cria_usuario(request, form)
            return HttpResponseRedirect(reverse('sgu:sgu'))
        else:
            return HttpResponseRedirect(reverse('sgu:cadastro_usuario'))
    else:
        contexto = {
            "form" : form_usuario(),
            "grupos" : Grupos.objects.all(),
        }            
        return render(request, "cadastro_usuario.html", contexto)

@login_required(login_url='sgu:login')
@user_passes_test(checa_sgu, login_url='sgu:erro_acesso', redirect_field_name=None)
def detalhes(request, username):
    if request.method == 'POST':
        button = request.POST.get("button")
        contexto = Gerencia_usuario.Atualiza_usuario(request, username)
        if button == "update_continue":
            return HttpResponseRedirect(reverse('sgu:detalhes', kwargs={'username':username}))
        elif button == "update":
            return HttpResponseRedirect(reverse('sgu:sgu'))
    else:
        perms = []
        grupo = []
        detalhes = Usuario.objects.get(username=username)
        perm = Permissions.objects.filter(usuario_id__id=detalhes.id)
        for i in Grupos.objects.all():
            i = str(i)
            grupo.append(i)
        for i in perm:
            i = str(i)
            perms.append(i)
        contexto = {
            "detalhes" : detalhes,
            "grupos" : grupo,
            "perms" : perms,
        }
    return render(request, "detalhes.html", contexto)

@login_required(login_url='sgu:login')
def chg_pass(request):
    if request.method == 'POST':
        pass_old = request.POST.get("pass_old")
        new_pass = request.POST.get("password")
        if User.check_password(request.user, pass_old):
            user = Usuario.objects.get(username=request.user)
            user.set_password(new_pass)
            user.save()
            return HttpResponseRedirect(reverse('sgu:logout'))
        else:
            print ("Senha incorreta")
    return render(request, "chg_pass.html")

def loginAdminPanel(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            usuario = Usuario.objects.get(username=username)
            if usuario.tipo == 'E':
                account = authenticate(username=username, password=password)
                if account is not None:
                    login(request, account)
                    return HttpResponseRedirect(reverse('principal'))
                else:
                    form = LoginForm()
                    context = {'form':form}
                    return render(request, 'login_admin.html', context)
            else:
                form = LoginForm()
                context = {'form':form}
                return render(request, 'login_admin.html', context)
        else:
            form = LoginForm()
            context = {'form':form}
            return render(request, 'login_admin.html', context)
    else:
        form = LoginForm()
        context = {'form':form}
    return render(request, "login_admin.html", context)

SGU/templates/baseLogin.html
<!DOCTYPE html>
<html>
<head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="/static/css/login.css">
        <link rel="stylesheet" href="/static/css/login1.css">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" type="image/x-icon" href="/static/favicon.ico">
        <title>
        {% block title %}

        {% endblock %}
        </title> 
</head>
<body>

<br><center><titulo>
{% block subtitulo %}


{% endblock %}
</titulo></center><br>

<section>
    <div class="inner">
    <form method="POST" action=" ">
            {% csrf_token %}
            <fonte>
                <center>
                   {% block conteudo %}

                   {% endblock %}
                    </fonte></center>
    </form>
    </div>
</section>

</body>
</html>

SGU/templates/cadastro_usuario.html
<!DOCTYPE html>
<html>
<head>
        <meta charset="UTF-8">
        {% extends 'base_admin.html' %}
                {% block title %}Cadastrar novo usuário{% endblock %}
                
</head>
<body>
    {% block main %}

    {% block subtitulo %}
    Cadastrar novo usuário
    {% endblock %}
    
    {% block conteudo2 %}
    {% load bootstrap3 %}
    <center>
        <form method="POST">
            {% csrf_token %}

            {% bootstrap_form form %}<br>

            {% for i in grupos %}
                <label>{{ i.nome }} <input type="checkbox" name="grupo" value="{{ i.nome }}"></label>&ensp;
            {% endfor %}
            <br><br><input type='submit' value='Registrar' class="btn btn-default"/>&ensp;&ensp;&ensp;&ensp;
            <button class="btn btn-default" onclick="goBack()">Cancelar</button>
    </form></center>
{% endblock %}
        {% endblock %}
</body>
</html>

SGU/templates/chg_pass.html
<!DOCTYPE html>
<html>
<head>
        <meta charset="UTF-8">
        {% extends 'base_admin.html' %}
                {% block title %} Mudar senha {% endblock %}
                
</head>
<body>
    {% load static %}

    {% block subtitulo %}
    Mudar senha
    {% endblock %}
    {% block conteudo3 %}
<div>
<section ><br><br>
    <form method="POST" action=" ">
            {% csrf_token %}
            <center>
            <label class="control-label">Senha anterior</label><br><br>
            <input type = "password" name = "pass_old" class="form-control"/><br><br>

            <label class="control-label">Nova senha</label><br><br>
            <input type = "password" name = "password" class="form-control"/><br><br>

            <input type='submit' value='Mudar' class="btn btn-default"/>
            </center>
    </form>
</section></div>
    {% endblock %}
</body>
</html>

SGU/templates/detalhes.html
<!DOCTYPE html>
<html>
<head>
        <meta charset="UTF-8">
        {% extends 'base_admin.html' %}
                {% block title %} Detalhes {% endblock %}
                
</head>
<body>
    {% load static %}
    {% block main %}

    {% block subtitulo %}
    Editar conta
    {% endblock %}
    
    {% block conteudo2 %}
    {% load bootstrap3 %}
    <form method="POST">
        {% csrf_token %}
        <center>
        <h3>Username: {{ detalhes.username }}</h3>
        <h3>Nome:</h3>
        <input type="text" value="{{ detalhes.nome }}" name="nome" class="form-manual">
        <h3>E-mail:</h3>
        <input type="text" value="{{ detalhes.email }}" name="email" class="form-manual"><br>
        <a href="{% url 'sgu:chg_pass' %}">Mudar minha senha</a><br><br>
        {% for i in grupos %}
            {% if i in perms %}
                <label>{{ i }} <input type="checkbox" name="grupo" value="{{ i }}" checked></label>
            {% else %}
                <label>{{ i }} <input type="checkbox" name="grupo" value="{{ i }}"></label>
            {% endif %}
        {% endfor %}
        {% if detalhes.is_active == True %}
            <p><label>Ativo <input type="checkbox" name="is_active" checked></label>
        {% else %}
            <p><label>Ativo <input type="checkbox" name="is_active"></label>
        {% endif %}
        <p><button type="submit" name="button" value="update" class="btn btn-outline btn-primary">Salvar</button>&ensp;&ensp;
        <button type="submit" name="button" value="update_continue" class="btn btn-outline btn-primary">Salvar e continuar editando</button>
    </form>
    </center>
    {% endblock %}
    {% endblock %}
</body>
</html>

SGU/templates/erro_acesso.html
<!DOCTYPE html>
<html>
<head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="/static/css/erro_acesso.css">
        <link rel="shortcut icon" type="image/x-icon" href="/static/favicon.ico">
        <title>Ooops.!</title>
</head>
<body>

    {% load static %}
	<br>
    <img src="{% static 'img/you-shall-not-pass.jpg' %}" alt="Não deu certo ¯\_(ツ)_/¯"><br>
    <center>Ooops.!</center>
    <center><p>Parece que você não tem permissão para estar aqui... ¯\_(ツ)_/¯ </p></center><br>
    <center><a href="/principal"><button class="btn btn-default" > Voltar </button> </a></center>

</body>
</html>


SGU/templates/login_admin.html
<!DOCTYPE html>
<html>
<head>
        <meta charset="UTF-8">
        {% extends 'baseLogin.html' %}
                {% block title %}  Login  {% endblock %}

</head>
<body>
    {% load static %}
    {% block subtitulo %} <titulo> Login </titulo> {% endblock %}  

    {% block conteudo %}
    {% load bootstrap3 %}
    {% bootstrap_css %}
    <label>Usuário</label>
    <br><input class="w3-input" name = "username" />
    <br><p><label>Senha</label>
    <input class="w3-input" type = "password" name = "password" /><p>
    <a href="{% url 'sgu:password_reset' %}">Esqueceu sua senha?</a><br><br>
    <button type="submit" class="button">
    {% bootstrap_icon "glyphicon glyphicon-log-in" %} &emsp;entrar</button>

    {% endblock %}    


</body>
</html>

SGU/templates/sgu.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="shortcut icon" type="image/x-icon" href="/static/favicon.ico">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        {% include 'menu_sup.html' %}
        <title>Cadastrar usuário</title>

        <!-- Bootstrap Core CSS -->
        <link href="/static/css/bootstrap.min.css" rel="stylesheet">

        <!-- MetisMenu CSS -->
        <link href="/static/css/metisMenu.min.css" rel="stylesheet">

        <!-- DataTables CSS -->
        <link href="/static/css/dataTables/dataTables.bootstrap.css" rel="stylesheet">

        <!-- DataTables Responsive CSS -->
        <link href="/static/css/dataTables/dataTables.responsive.css" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="/static/css/startmin.css" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="/static/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    </head>
    <body>
</nav></div>

<!--AREA TABELA -->

<!--AREA TABELA -->

<!--AREA TABELA -->

        <div id="page-wrapper" style="min-height: 570px;margin-left:0px">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">Sistema de gerenciamento de usuário</h1>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                            <div class="panel-body">
                                <center><h4><a href="{% url 'sgu:cadastro_usuario' %}"> Cadastrar usuário</a></h4></center>
                            <br>
                            <form method="POST">
                                {% csrf_token %}
                                <h2>Usuários Internos</h2>
                                <div class="dataTable_wrapper">
                                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                        <thead>
                                            <tr>
                                                <th> Nome </th>
                                                <th> Username </th>
                                                <th> E-Mail </th>
                                                <th> Deletar </th>
                                                <th> Editar </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for i in users %}
                                        {% if i.tipo == 'E' %}
                                            <td>{{ i.nome }}</td> 
                                            <td> {{ i.username }} </td>
                                            <td> {{ i.email }} </td> 
                                            <td><button type="submit" name="delete" value="{{ i.id }}">Delete</button></td>
                                            <td><a href="{{ i.get_absolute_url }}">Editar</a></td>
                                        </tr>
                                        {% endif %}
                                        {% endfor %}

                                        </tbody>
                                    </table>
                                </div>
                                <h2>Clientes</h2>
                                <div class="dataTable_wrapper">
                                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                        <thead>
                                            <tr>
                                                <th> Nome </th>
                                                <th> Username </th>
                                                <th> E-Mail </th>
                                                <th> Deletar </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for i in users %}
                                        {% if i.tipo == 'C' %}
                                            <td>{{ i.nome }}</td> 
                                            <td> {{ i.username }} </td>
                                            <td> {{ i.email }} </td> 
                                            <td><button type="submit" name="delete" value="{{ i.id }}">Delete</button></td>
                                        </tr>
                                        {% endif %}
                                        {% endfor %}

                                        </tbody>
                                    </table>
                                </div>
                                <!-- /.table-responsive -->

        <!-- jQuery -->
        <script src="/static/js/jquery.min.js"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="/static/js/bootstrap.min.js"></script>

        <!-- Metis Menu Plugin JavaScript -->
        <script src="/static/js/metisMenu.min.js"></script>

        <!-- DataTables JavaScript -->
        <script src="/static/js/dataTables/jquery.dataTables.min.js"></script>
        <script src="/static/js/dataTables/dataTables.bootstrap.min.js"></script>

        <!-- Custom Theme JavaScript -->
        <script src="/static/js/startmin.js"></script>

        <!-- Page-Level Demo Scripts - Tables - Use for reference -->
        <script>
            $(document).ready(function() {
                $('#dataTables-example').DataTable({
                        responsive: true
                });
            });
        </script>

    </body>
</html>