NGKS_Shop/urls.py
from django.conf.urls import url, include
from core.views import *
from django.contrib.auth.views import logout

urlpatterns = [
    #ecommerce
    url(r'^$', index, name='index'),
    url(r'^lista_produtos/', lista_produtos, name='lista_produtos'),
    url(r'^categoria/(?P<slug>[\w_-]+)/$', loja_categoria, name='loja_categoria'),
    url(r'^produtos/(?P<slug>[\w_-]+)/$', loja_produto, name='loja_produto'),
    url(r'^registro/', registro, name='cadastro_cliente'),
    url(r'^login/$', loginEcommerce, name='loginEcommerce'),
    url(r'^logout/$', logout, {'next_page': 'index'} ,name='logout'),
    url(r'^contato/$', contato,name='contato'),
    url(r'^checkout/', include(('checkout.urls', 'checkout'), namespace='checkout')),
    #administrativo
    url(r'^principal/$', principal, name='principal'),
    url(r'^sgu/', include(('SGU.urls', 'sgu'), namespace='sgu')),
    url(r'^estoque/$', estoque, name='estoque'),
    url(r'^fluxo/$', fluxo, name='fluxo'),
    url(r'^pedidos/$', pedidos, name='pedidos'),
    url(r'^catalogo/', include(('catalogo.urls', 'catalogo'), namespace='catalogo')),
]

SGU/urls.py
from django.conf.urls import url
from SGU.views import *
from django.contrib.auth.views import login,logout
from SGU import auth as auth_views 

urlpatterns = [
    url(r'^$', sgu, name='sgu'),
    url(r'^chg_pass/', chg_pass, name='chg_pass'),#verificar essa URL
    url(r'^(?P<username>.*)/detalhes', detalhes, name='detalhes'),
    url(r'^cadastro_usuario/', cadastro_usuario, name='cadastro_usuario'),
    url(r'^login_admin/$', loginAdminPanel, name='login'),
    url(r'^logout/', logout, {'next_page': 'sgu:login'} ,name='logout'),
    url(r'^erro_acesso/', erro_acesso, name='erro_acesso'),
    url(r'^password_reset/$', auth_views.password_reset, {'subject_template_name': 'password_reset_subject.txt'}, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
]

catalogo/urls.py
from django.conf.urls import url
from catalogo.views import *

urlpatterns = [
    url(r'^$', catalogo, name='catalogo'),
    url(r'categorias/$', categorias, name='categorias'),
    url(r'^(?P<slug>[\w_-]+)/categoria_detalhes', categoria_detalhes, name='categoria_detalhes'),
    url(r'adiciona_categoria/$', adiciona_categoria, name='adiciona_categoria'),
    url(r'^produtos/$', produtos, name='produtos'),
    url(r'^(?P<slug>[\w_-]+)/produto_detalhes', produto_detalhes, name='produto_detalhes'),
    url(r'adiciona_produto/$', adiciona_produto, name='adiciona_produto'),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
#coding=utf-8

from django import forms
from django.core.mail import send_mail
from django.conf import settings


class contato_forms(forms.Form):

    nome = forms.CharField(label='Nome')
    email = forms.EmailField(label='E-mail')
    messagem = forms.CharField(label='Mensagem', widget=forms.Textarea())

    def send_mail(self):
        nome = self.cleaned_data['nome']
        email = self.cleaned_data['email']
        messagem = self.cleaned_data['messagem']
        messagem = 'Nome: {0}\nE-mail:{1}\n{2}'.format(nome, email, messagem)
        send_mail(
            'Contato da NGKS_Shop', messagem, settings.DEFAULT_FROM_EMAIL,
            [settings.DEFAULT_FROM_EMAIL]
        )

core/views.py
from django.shortcuts import render
from src.usuario import Gerencia_permissao
from django.contrib.auth.decorators import login_required, user_passes_test
from SGU.models import Grupos, Usuario, Permissions, Cliente
from catalogo.models import Categoria, Produto
from django.contrib.auth import authenticate
from django.contrib.auth.views import login
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from SGU.forms import form_cliente, LoginForm, form_usuario
from django.urls import reverse, reverse_lazy
from src.usuario import Gerencia_usuario, Gerencia_permissao
from django.views.generic import CreateView
from django.http import HttpResponse
from django.core.mail import send_mail
from django.conf import settings
from .forms import contato_forms
from django.views.generic import View, TemplateView, CreateView
from django.contrib import messages


# Create your views here.

def check_estoque(request):
    return 'ESTOQUE' in Gerencia_permissao.Pega_grupo(request)

def check_fluxo(request):
    return 'FLUXO' in Gerencia_permissao.Pega_grupo(request)

def check_pedidos(request):
    return 'PEDIDOS' in Gerencia_permissao.Pega_grupo(request)

def check_empresa(request):
    user = Usuario.objects.get(username=request.username)
    return user.tipo == 'E'

def index(request):
    return render(request, 'index.html')

def lista_produtos(request):
    contexto = {
        'lista_produtos': Produto.objects.all()
    }
    return render(request, 'lista_produtos.html', contexto)

def loja_categoria(request, slug):
    categoria = Categoria.objects.get(slug=slug)
    contexto = {
        'categoria_corrente': categoria,
        'lista_produtos': Produto.objects.filter(categoria=categoria),
    }
    return render(request, 'categoria.html', contexto)

def loja_produto(request, slug):
    produto = Produto.objects.get(slug=slug)
    contexto = {
        'produto': produto,
    }
    return render(request, 'produto.html', contexto)

def loginEcommerce(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            usuario = Usuario.objects.get(username=username)
            account = authenticate(username=username, password=password)
            if account is not None:
                login(request, account)
                return HttpResponseRedirect(reverse('index'))
            else:
                form = LoginForm()
                context = {'form':form}
                return render(request, 'login.html', context)
        else:
            form = LoginForm()
            context = {'form':form}
            return render(request, 'login.html', context)
    else:
        form = LoginForm()
        context = {'form':form}
        return render(request, 'login.html', context)

class cadastro_cliente(CreateView):
    form_class = form_cliente
    template_name = 'registro.html'
    success_url = reverse_lazy('index')

registro = cadastro_cliente.as_view() 

def contato(request):
    success = False
    form = contato_forms(request.POST or None)
    if form.is_valid():
        form.send_mail()
        success = True
    else:
        messages.error(request, 'Formulário inválido')
    contexto = {
        'form': form,
        'success': success
    }
    return render(request, 'contato.html', contexto)


@login_required(login_url='sgu:login')
@user_passes_test(check_empresa, login_url='sgu:erro_acesso', redirect_field_name=None)
def principal(request):
    return render(request, "principal.html")

@login_required(login_url='sgu:login')
@user_passes_test(check_estoque, login_url='sgu:erro_acesso', redirect_field_name=None)
def estoque(request):
    return render(request, "estoque.html")

@login_required(login_url='sgu:login')
@user_passes_test(check_fluxo, login_url='sgu:erro_acesso', redirect_field_name=None)
def fluxo(request):
    return render(request, "fluxo.html")

@login_required(login_url='sgu:login')
@user_passes_test(check_pedidos, login_url='sgu:erro_acesso', redirect_field_name=None)
def pedidos(request):
    return render(request, "pedidos.html")

core/templates/base_admin.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        {% include 'menu_sup.html' %}
                    <!-- ###################### TITLE  #########################--> 
        <title>
        {% block title %}

        {% endblock %}
        </title>

        <!-- Bootstrap Core CSS -->
		<link rel="shortcut icon" type="image/x-icon" href="/static/favicon.ico">
        
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link href="/static/css/bootstrap.min.css" rel="stylesheet">

        <!-- MetisMenu CSS -->
        <link href="/static/css/metisMenu.min.css" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="/static/css/startmin.css" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="/static/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="/static/css/site.css" rel="stylesheet">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
                <!-- /.navbar-top-links -->
                {% block barra_lateral %}
                <div class="navbar-default sidebar" role="navigation">

                </div>
                {% endblock %}
                
                </div>
                <!-- /.navbar-static-side -->
            </nav>

            <!-- Page Content -->
            <div id="page-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <h1 class="page-header">
                                <!-- ###################### SUBTITULO  #########################--> 
                                {% block subtitulo %}

                                {% endblock %}

                            </h1>
                        </div>
                        <!-- /.col-lg-12 -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- ###################### CONTEUDO DA PAG.  #########################--> 

                <div class="column side">
                {% block conteudo1 %}

                {% endblock %}
                </div>

                <div class="column middle">
                {% block conteudo2 %}

                {% endblock %}
                </div>

                <div class="column side">
                {% block conteudo3 %}

                {% endblock %}
                </div>                

                <div class="column tab">
                {% block conteudo4 %}

                {% endblock %}
                <!-- /.container-fluid -->
            </div>
            <!-- /#page-wrapper -->

        </div>
        <!-- /#wrapper -->

        <!-- jQuery -->
        <script src="/static/js/jquery.min.js"></script>
        
        <!-- VOLTAR A PÁGINA -->
        <script>function goBack() {window.history.back();}</script>
        
        <!-- Bootstrap Core JavaScript -->
        <script src="/static/js/bootstrap.min.js"></script>

        <!-- Metis Menu Plugin JavaScript -->
        <script src="/static/js/metisMenu.min.js"></script>

        <!-- Custom Theme JavaScript -->
        <script src="/static/js/startmin.js"></script>

    </body>
</html>

core/templates/estoque.html
<!DOCTYPE html>
<html>
<head>
        <meta charset="UTF-8">
        {% extends 'base_admin.html' %}
                {% block title %}  Estoque  {% endblock %}
                
</head>
<body>
    {% load static %}
    {% block main %}
    
    {% block subtitulo %}
    Estoque
    {% endblock %}

    {% block barra_lateral %}
                <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                            <li>
                                <a href="#"></a>
                            </li>                            
                            <li>
                                <a href="{% url 'catalogo:adiciona_produto'  %}">Cadastrar produto</a>
                            </li>
                            <li>
                                <a href="{% url 'catalogo:adiciona_categoria' %}"> Cadastrar categoria</a>
                            </li>                              
                        </ul>
                    </div>
                </div>
    {% endblock %}
    
	{% block conteudo1 %}
    <center>
    <fonteprincipal> Oi </fonteprincipal>
    </center>
    {% endblock %}

    {% block conteudo2 %}
    <center>
    <fonteprincipal> Oi </fonteprincipal>
    </center>
    {% endblock %}

    {% block conteudo3 %}
    <center>
    <fonteprincipal> Oi </fonteprincipal>
    </center>
    {% endblock %}




    {% endblock %}
</body>
</html>

core/templates/fluxo.html
	<!DOCTYPE html>
<html>
<head>
        <meta charset="UTF-8">
        {% extends 'base_admin.html' %}
                {% block title %}  Fluxo de caixa  {% endblock %}
                
</head>
<body>
    {% load static %}
    {% block main %}

    {% block subtitulo %}
    Fluxo de caixa
    {% endblock %}    
    
    {% block barra_lateral %}
                <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                            <li>
                                <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Charts<span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href="flot.html">Flot Charts</a>
                                    </li>
                                    <li>
                                        <a href="morris.html">Morris.js Charts</a>
                                    </li>
                                </ul>
                                <!-- /.nav-second-level -->
                            </li>
                            <li>
                                <a href="tables.html"><i class="fa fa-table fa-fw"></i> Tables</a>
                            </li>
                            <li>
                                <a href="forms.html"><i class="fa fa-edit fa-fw"></i> Forms</a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-wrench fa-fw"></i> UI Elements<span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href="panels-wells.html">Panels and Wells</a>
                                    </li>
                                    <li>
                                        <a href="buttons.html">Buttons</a>
                                    </li>
                                    <li>
                                        <a href="notifications.html">Notifications</a>
                                    </li>
                                    <li>
                                        <a href="typography.html">Typography</a>
                                    </li>
                                    <li>
                                        <a href="icons.html"> Icons</a>
                                    </li>
                                    <li>
                                        <a href="grid.html">Grid</a>
                                    </li>
                                </ul>
                                <!-- /.nav-second-level -->
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-sitemap fa-fw"></i> Multi-Level Dropdown<span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href="#">Second Level Item</a>
                                    </li>
                                    <li>
                                        <a href="#">Second Level Item</a>
                                    </li>
                                    <li>
                                        <a href="#">Third Level <span class="fa arrow"></span></a>
                                        <ul class="nav nav-third-level">
                                            <li>
                                                <a href="#">Third Level Item</a>
                                            </li>
                                            <li>
                                                <a href="#">Third Level Item</a>
                                            </li>
                                            <li>
                                                <a href="#">Third Level Item</a>
                                            </li>
                                            <li>
                                                <a href="#">Third Level Item</a>
                                            </li>
                                        </ul>
                                        <!-- /.nav-third-level -->
                                    </li>
                                </ul>
                                <!-- /.nav-second-level -->
                            </li>
                        </ul>
                    </div>
                    <!-- /.sidebar-collapse -->
                </div>
    {% endblock %}

    {% block conteudo1 %}
    <center>
    <fonteprincipal> Oi </fonteprincipal>
    </center>
    {% endblock %}

    {% block conteudo2 %}
    <center>
    <fonteprincipal> Oi </fonteprincipal>
    </center>
    {% endblock %}
    

    {% block conteudo3 %}
    <center>
    <fonteprincipal> Oi </fonteprincipal>
    </center>
    {% endblock %}

    
    {% endblock %}
</body>
</html>

core/templates/lista_produtos.html
{% extends "base.html" %}
{% load pagination %}

{% block tittle %} Lista de Produtos | {{ block.super }} {% endblock %}

{% block pagina %}
<div class="page-header">
    <h1>Produtos</h1>
</div>
<div class="row">
    {% for produto in lista_produtos %}
    {% include "catalogo_produto.html" %}
    {% endfor %}
</div>

{% pagination request paginator page_obj %}
{% endblock %}

core/templates/login.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block tittle %} Login | {{ block.super }} {% endblock %}

{% block pagina %}
    {% load bootstrap3 %}
    {% bootstrap_css %}
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="page-header">
                <h1>Entrar</h1><br><br>
            </div>
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    {{ error }}
                </div>
            {% endfor %}
            <form class="form-horizontal" method="POST">
                {% csrf_token %}
                    <div class="form-group{% if form.username.errors %} has-erro{% endif %}">
                      <label for="{{ form.username.auto_id }}" class="col-md-3 control-label">{{ form.username.label }}</label>
                      <div class="col-md-9">
                        {% render_field form.username class="form-control" %}
                        {% for error in form.username.errors %}
                            <span class="help-block">{{ error }}</span>
                        {% endfor %}
                      </div>
                    </div>
                    <div class="form-group{% if form.password.errors %} has-erro{% endif %}">
                      <label for="{{ form.password.auto_id }}" class="col-md-3 control-label">{{ form.password.label }}</label>
                      <div class="col-md-9">
                        {% render_field form.password class="form-control" %}
                        {% for error in form.password.errors %}
                            <span class="help-block">{{ error }}</span>
                        {% endfor %}
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="col-md-9 col-md-offset-3">
                        <button type="submit" class="btn btn-primary">Enviar</button>
                      </div>
                    </div>
            </form><br><br>
    </div></div></div>
    <br><br>
{% endblock %}

core/templates/menu_sup.html
        <div id="wrapper">
            <!-- Navigation -->
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                          <div class="navbar-header">
                            <a class="navbar-brand" href="/principal/">PRINCIPAL</a>
                            {% for i in perm %}
                            {% for j in grupo %}
                            {% if i.groups in j.nome%}
                            <a class="navbar-brand" href="{{ j.link }}">{{ i }}</a>
                            {% endif %}
                            {% endfor %}
                            {% endfor %}
                          </div>
                          <ul class="nav navbar-nav navbar-left navbar-top-links">
                            <li><a href="{% url 'index' %}"><i class="fa fa-home fa-fw"></i> E-commerce </a></li>
                            </ul>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <ul class="nav navbar-right navbar-top-links">
                    <li class="dropdown navbar-inverse">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-bell fa-fw"></i> <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu dropdown-alerts">
                            <li>
                                <a href="#">
                                    <div>
                                        <i class="fa fa-comment fa-fw"></i> New Comment
                                        <span class="pull-right text-muted small">4 minutes ago</span>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <div>
                                        <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                        <span class="pull-right text-muted small">12 minutes ago</span>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <div>
                                        <i class="fa fa-envelope fa-fw"></i> Message Sent
                                        <span class="pull-right text-muted small">4 minutes ago</span>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <div>
                                        <i class="fa fa-tasks fa-fw"></i> New Task
                                        <span class="pull-right text-muted small">4 minutes ago</span>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <div>
                                        <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                        <span class="pull-right text-muted small">4 minutes ago</span>
                                    </div>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a class="text-center" href="#">
                                    <strong>See All Alerts</strong>
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-user fa-fw"></i> {{ user }} <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="/sgu/{{ user }}/detalhes"><i class="fa fa-gear fa-fw"></i> Settings</a>
                            </li>
                            <li class="divider"></li>
                            <li><a href="{% url 'sgu:logout' %}"><i class="fa fa-sign-out fa-fw"></i> Logout </a>
                            </li>
                        </ul>
                    </li>
                </ul>

core/templates/pagination.html
<div class="row">
    <div class="col-md-12"> 
        <nav>
            <ul class="pagination">
                {% for page in paginator.page_range %}
                    <li><a href="?page={{ page }}">{{ page }}</a></li>
                {% endfor %}
            </ul>
        </nav>
    </div>
</div>

core/templates/pedidos.html
<!DOCTYPE html>
<html>
<head>
        <meta charset="UTF-8">
        {% extends 'base_admin.html' %}
                {% block title %}  Pedidos  {% endblock %}
                
</head>
<body>
    {% load static %}
    {% block main %}

    {% block subtitulo %}
    Pedidos
    {% endblock %}

    {% block barra_lateral %}
                <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                            <li>
                                <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Charts<span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href="flot.html">Flot Charts</a>
                                    </li>
                                    <li>
                                        <a href="morris.html">Morris.js Charts</a>
                                    </li>
                                </ul>
                                <!-- /.nav-second-level -->
                            </li>
                            <li>
                                <a href="tables.html"><i class="fa fa-table fa-fw"></i> Tables</a>
                            </li>
                            <li>
                                <a href="forms.html"><i class="fa fa-edit fa-fw"></i> Forms</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.sidebar-collapse -->
                </div>
    {% endblock %}
    
    {% block conteudo1 %}
    <center>
    <fonteprincipal> 
    Oi<br>
    Oi<br>
    Oi<br>
    Oi<br>
    Oi<br>
    Oi<br>
    </fonteprincipal>
    </center>
    {% endblock %}

    {% block conteudo2 %}
    <center>
    <fonteprincipal> Oi </fonteprincipal>
    </center>
    {% endblock %}

    {% block conteudo3 %}
    <center>
    <fonteprincipal> Oi </fonteprincipal>
    </center>
    {% endblock %}




    {% endblock %}
</body>
</html>

core/templates/principal.html
<!DOCTYPE html>
<html>
<head>
        <meta charset="UTF-8">
        {% extends 'base_admin.html' %}
                {% block title %}  Home  {% endblock %}
                
</head>
<body>
    {% load static %}
    {% block main %}

	{% block subtitulo %}
    Olá {{ user }}
    {% endblock %}

    {% block barra_lateral %}
    <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                            <li>
                                <a href="{% url 'index' %}"><i class="fa fa-home fa-fw"></i> E-commerce </a>
                            </li>
    {% endblock %}

    {% block conteudo1 %}
    <center>
    <fonteprincipal> oi </fonteprincipal>
    </center>
    {% endblock %}

    {% block conteudo2 %}
        <fonteprincipal> BláBláBláBláBláBlá<br>BláBláBláBláBláBlá </fonteprincipal></fonteprincipal></center>
    {% endblock %}


    {% endblock %}
</body>
</html>

core/templates/registro.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block tittle %} Registre-se | {{ block.super }} {% endblock %}

{% block pagina %}
    {% load bootstrap3 %}
    {% bootstrap_css %}

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="page-header">
                <h1>Registre-se</h1>
            </div>
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    {{ error }}
                </div>
            {% endfor %}
            <form class="form-horizontal" method="POST">
                {% csrf_token %}
                <fieldset>
                    {% for campo in form %}
                    <div class="form-group{% if campo.errors %} has-erro{% endif %}">
                      <label for="{{ campo.auto_id }}" class="col-md-3 control-label">{{ campo.label }}</label>
                      <div class="col-md-9">
                        {% render_field campo class="form-control" %}
                        {% for error in campo.errors %}
                            <span class="help-block">{{ error }}</span>
                        {% endfor %}
                      </div>
                    </div>                    
                    {% endfor %}
                    <div class="form-group">
                      <div class="col-md-9 col-md-offset-3">
                        <center><button type="submit" class="btn btn-primary">Enviar</button></center>
                      </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
{% endblock %}